services:
  satissavebak:
    container_name: satissavebak
    # No image available, build from source
    build:
      context: ./src
    restart: unless-stopped
    environment:
      - LOG_LEVEL
      - CRON_SCHEDULE
      - GIT_REPO_URL_FOR_SIMBASHLOG_NOTIFIER
      - SATISFACTORY_SAVE_GAMES_PATH
      - SATISFACTORY_BLUEPRINTS_PATH
      - GIT_REPO_URL_FOR_SATISFACTORY_BACKUP
    volumes:
      # Logs - Comment out to disable logging to host
      - type: bind
        source: ./volumes/logs
        target: /var/log
        bind:
          create_host_path: true
      # simbashlog notifier config - Comment out if no simbashlog notifier is used
      - type: bind
        source: ./volumes/config
        target: /root/.config/simbashlog-notifier
        bind:
          create_host_path: true
      # SSH
      - type: bind
        source: ./volumes/ssh
        target: /root/.ssh
        read_only: true
      # Satisfactory Save Games
      - type: bind
        source: $SATISFACTORY_SAVE_GAMES_PATH
        target: /mnt/satisfactory/saves
        read_only: true
      # Satisfactory Blueprints
      - type: bind
        source: $SATISFACTORY_BLUEPRINTS_PATH
        target: /mnt/satisfactory/blueprints
        read_only: true
